name = "nexus-shop"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
main = ".vercel/output/static/_worker.js/index.js"

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "ecommerce-db"
database_id = "beb4060b-2b12-4960-a23b-ca5fd5f87a86" # You will replace this after running `wrangler d1 create ecommerce-db`
